[package]
name = "advent-of-code-2024"
version = "0.1.0"
edition = "2021"

[dependencies]
ratatui = "0.29.0"
tokio = { version = "1", features = ["full"] }
crossterm = "0.28.1"
regex = "1.11.1"
tui-tree-widget = "0.23.0"
